FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirement.txt .
RUN pip install --no-cache-dir -r requirement.txt

# Встановлюємо браузери ТА всі системні Linux-бібліотеки (--with-deps) під час збірки!
RUN playwright install --with-deps

COPY . .

CMD ["pytest", "-m", "ui_test", "-v", "-s"]